openapi: 3.0.3
info:
  title: SpecFlux API
  description: |
    API for SpecFlux - AI-Powered Multi-Repo Development Orchestrator.

    SpecFlux orchestrates Claude Code agents across multiple repositories
    with spec-driven workflows and configurable pipelines.

    ## API Conventions

    - All responses use a consistent envelope: `{ success: boolean, data?: T, error?: Error }`
    - List endpoints support pagination via `page` and `limit` query parameters
    - PATCH is used for partial updates, PUT for full resource replacement
    - 204 No Content is returned for successful DELETE operations
    - Error responses include machine-readable codes and human-readable messages

    ## Status Codes

    - 200: Success
    - 201: Created
    - 204: No Content (successful DELETE)
    - 400: Bad Request (validation errors)
    - 401: Unauthorized
    - 404: Not Found
    - 409: Conflict (state conflicts, duplicate resources)
    - 500: Internal Server Error
  version: 1.0.0
  contact:
    name: SpecFlux
    url: https://github.com/cliangdev/specflux

servers:
  - url: http://localhost:3000/api
    description: Local development server

tags:
  - name: Health
    description: Health check endpoints
  - name: Users
    description: User profile management
  - name: Projects
    description: Project management
  - name: Releases
    description: Release management for roadmap planning
  - name: Epics
    description: Epic management (groups of related tasks)
  - name: Tasks
    description: Task management and agent orchestration
  - name: Repositories
    description: Repository management
  - name: Notifications
    description: Notification management
  - name: Files
    description: File operations within project directories
  - name: Agents
    description: Agent definition management
  - name: Skills
    description: Skill definition management
  - name: MCP Servers
    description: MCP server configuration management

paths:
  # Health
  /health:
    $ref: './paths/health.yaml#/health'

  # Users
  /users/me:
    $ref: './paths/users.yaml#/users-me'

  # Projects
  /projects:
    $ref: './paths/projects.yaml#/projects'
  /projects/{id}:
    $ref: './paths/projects.yaml#/projects-id'
  /projects/{id}/config:
    $ref: './paths/projects.yaml#/projects-id-config'
  /projects/{id}/dashboard:
    $ref: './paths/projects.yaml#/projects-id-dashboard'
  /projects/{id}/stats:
    $ref: './paths/projects.yaml#/projects-id-stats'

  # Releases (nested under projects)
  /projects/{id}/releases:
    $ref: './paths/releases.yaml#/projects-id-releases'
  /releases/{id}:
    $ref: './paths/releases.yaml#/releases-id'
  /releases/{id}/roadmap:
    $ref: './paths/releases.yaml#/releases-id-roadmap'

  # Epics (nested under projects)
  /projects/{id}/epics:
    $ref: './paths/epics.yaml#/projects-id-epics'
  /epics/{id}:
    $ref: './paths/epics.yaml#/epics-id'
  /epics/{id}/tasks:
    $ref: './paths/epics.yaml#/epics-id-tasks'
  /epics/{id}/progress:
    $ref: './paths/epics.yaml#/epics-id-progress'

  # Tasks (nested under projects)
  /projects/{id}/tasks:
    $ref: './paths/tasks.yaml#/projects-id-tasks'
  /tasks/{id}:
    $ref: './paths/tasks.yaml#/tasks-id'
  /tasks/{id}/assignee:
    $ref: './paths/tasks.yaml#/tasks-id-assignee'
  /tasks/{id}/dependencies:
    $ref: './paths/tasks.yaml#/tasks-id-dependencies'
  /tasks/{id}/dependencies/{dep_id}:
    $ref: './paths/tasks.yaml#/tasks-id-dependencies-dep-id'
  /tasks/{id}/agent:
    $ref: './paths/tasks.yaml#/tasks-id-agent'
  /tasks/{id}/agent/output:
    $ref: './paths/tasks.yaml#/tasks-id-agent-output'
  /tasks/{id}/changes:
    $ref: './paths/tasks.yaml#/tasks-id-changes'
  /tasks/{id}/diff:
    $ref: './paths/tasks.yaml#/tasks-id-diff'
  /tasks/{id}/review:
    $ref: './paths/tasks.yaml#/tasks-id-review'
  /tasks/{id}/create-pr:
    $ref: './paths/tasks.yaml#/tasks-id-create-pr'
  /tasks/{id}/approve:
    $ref: './paths/tasks.yaml#/tasks-id-approve'
  /tasks/{id}/file-changes:
    $ref: './paths/tasks.yaml#/tasks-id-file-changes'

  # Repositories (nested under projects)
  /projects/{id}/repositories:
    $ref: './paths/repositories.yaml#/projects-id-repositories'
  /repositories/{id}:
    $ref: './paths/repositories.yaml#/repositories-id'
  /repositories/{id}/sync:
    $ref: './paths/repositories.yaml#/repositories-id-sync'
  /repositories/validate:
    $ref: './paths/repositories.yaml#/repositories-validate'

  # Notifications (nested under projects)
  /projects/{id}/notifications:
    $ref: './paths/notifications.yaml#/projects-id-notifications'
  /projects/{id}/notifications/read-all:
    $ref: './paths/notifications.yaml#/projects-id-notifications-read-all'
  /notifications/{id}:
    $ref: './paths/notifications.yaml#/notifications-id'

  # Files (nested under projects)
  /projects/{id}/files:
    $ref: './paths/files.yaml#/projects-id-files'
  /files/{path}:
    $ref: './paths/files.yaml#/files-path'

  # Agents (nested under projects)
  /projects/{id}/agents:
    $ref: './paths/agents.yaml#/projects-id-agents'
  /projects/{id}/agents/sync:
    $ref: './paths/agents.yaml#/projects-id-agents-sync'
  /projects/{id}/default-agent:
    $ref: './paths/agents.yaml#/projects-id-default-agent'
  /agents/{id}:
    $ref: './paths/agents.yaml#/agents-id'

  # Skills (nested under projects)
  /projects/{id}/skills:
    $ref: './paths/skills.yaml#/projects-id-skills'
  /projects/{id}/skills/sync:
    $ref: './paths/skills.yaml#/projects-id-skills-sync'
  /skills/{id}:
    $ref: './paths/skills.yaml#/skills-id'

  # MCP Servers (nested under projects)
  /projects/{id}/mcp-servers:
    $ref: './paths/mcp-servers.yaml#/projects-id-mcp-servers'
  /projects/{id}/mcp-servers/sync:
    $ref: './paths/mcp-servers.yaml#/projects-id-mcp-servers-sync'
  /mcp-servers/{id}:
    $ref: './paths/mcp-servers.yaml#/mcp-servers-id'
  /mcp-servers/{id}/toggle:
    $ref: './paths/mcp-servers.yaml#/mcp-servers-id-toggle'

components:
  schemas:
    $ref: './schemas/_index.yaml'

  securitySchemes:
    UserIdHeader:
      type: apiKey
      in: header
      name: X-User-Id
      description: User ID header for desktop app authentication

security:
  - UserIdHeader: []
