Project:
  type: object
  properties:
    id:
      type: integer
    project_id:
      type: string
      description: Unique project identifier
    name:
      type: string
    local_path:
      type: string
    git_remote:
      type: string
      nullable: true
    workflow_template:
      type: string
      enum: [startup-fast, design-first, full-lifecycle, custom]
    owner_user_id:
      type: integer
    created_at:
      type: string
      format: date-time
    updated_at:
      type: string
      format: date-time
  required:
    - id
    - project_id
    - name
    - local_path
    - workflow_template
    - owner_user_id
    - created_at
    - updated_at

CreateProjectRequest:
  type: object
  properties:
    name:
      type: string
      minLength: 1
      maxLength: 100
    local_path:
      type: string
    git_remote:
      type: string
      nullable: true
    workflow_template:
      type: string
      enum: [startup-fast, design-first, full-lifecycle]
      default: startup-fast
  required:
    - name
    - local_path

UpdateProjectRequest:
  type: object
  properties:
    name:
      type: string
      minLength: 1
      maxLength: 100
    git_remote:
      type: string
      nullable: true

ProjectConfig:
  type: object
  properties:
    id:
      type: integer
    project_id:
      type: integer
    workflow_template:
      type: string
    workflow_config:
      type: object
      description: JSON workflow configuration
    approval_config:
      type: object
      description: JSON approval gates configuration
    created_at:
      type: string
      format: date-time
    updated_at:
      type: string
      format: date-time
  required:
    - id
    - project_id
    - workflow_template
    - created_at
    - updated_at

UpdateProjectConfigRequest:
  type: object
  properties:
    workflow_template:
      type: string
      enum: [startup-fast, design-first, full-lifecycle, custom]
    workflow_config:
      type: object
    approval_config:
      type: object

DashboardResponse:
  type: object
  properties:
    active_tasks:
      type: array
      items:
        $ref: '../schemas/task.yaml#/Task'
    pending_review:
      type: array
      items:
        $ref: '../schemas/task.yaml#/Task'
    repositories:
      type: array
      items:
        $ref: '../schemas/repository.yaml#/Repository'
    notifications_count:
      type: integer
  required:
    - active_tasks
    - pending_review
    - repositories
    - notifications_count

ProjectStats:
  type: object
  properties:
    total_tasks:
      type: integer
    tasks_by_status:
      type: object
      additionalProperties:
        type: integer
    total_epics:
      type: integer
    epics_by_status:
      type: object
      additionalProperties:
        type: integer
    active_agents:
      type: integer
    completed_today:
      type: integer
  required:
    - total_tasks
    - tasks_by_status
    - total_epics
    - epics_by_status
    - active_agents
    - completed_today
